### ISSUE TITLE
How do we implement this

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [PoomSmart/Burst-Mode#2]
I am using AVCaptureSession in my project. How do I add this code to it? Can you make a simple example project to use as reference?

**Comment by PoomSmart** [comment]
There is a plenty of suggestions on Stackoverflow for how to mimic burst capture. One suggestion from this reply, having a method that takes a photos and running that continuously via `NSTimer`. Anyway, this issue is not considered Burst mode tweak's issues. It also shouldn't be in any relation with such jailbreak tweak which modify on top of complex code.
